INSERT INTO ROLES(NAME)
VALUES ('admin');

INSERT INTO USERS(
    NAME, EMAIL, PASSWORD, ROLE_ID
)
VALUES (
    'SUPER ADMIN', 'sa@test.com', '$2a$12$FvZKvwg8H0mRcE7XGi4hV.f0g1QifWznxQ9XUSOFcPSCeLPz0AOPq', 1
);